### ISSUE TITLE
It does not work with negative XIRR

### ISSUE THREAD

**Issue by helenhash** [joutvhu/xirr#1]
It doesn't get correct value for below data.  
@Test
    public void xirr_tc_1() {
        Xirr xirr = Xirr.instance();
        List<Transaction> transactions = Arrays.asList(
                new Transaction(-6565763.490000000000000, "2018-10-02"),
                new Transaction( -91577.340000000000000, "2018-10-02"),
                new Transaction(317505.630000000000000, "2023-09-30"),
                new Transaction( 4428.480000000000000, "2023-09-30")
        );
        double r = xirr.xirr(transactions);
    }

**Comment by joutvhu** [comment]
Fixed in version [v1.0.5](https://github.com/joutvhu/xirr/releases/tag/v1.0.5)
